<h2>Articles presque épuisés</h2>
<table class="table table-sm table-striped table-hover">
    <tr>
        <th class="px-3">Produit</th>
        <th class="px-3">Catégorie</th>
        <th class="px-3">Échelle</th>
        <th class="px-3">Pièces restantes</th>
    </tr>
    <!-- POUR CHAQUE $outOfStock : -->
    <?php foreach($outOfStock as $product) : ?>
        <tr>
            <td class="px-3">
                <a href="product.php?id=<?=$product['productCode']?>">
                  <?=$product['productName']?>
                </a>
            </td>
            <td class="px-3"><?=$product['productLine']?></td>
            <td class="px-3"><?=$product['productScale']?></td>
            <td class="px-3"><?=$product['quantityInStock']?></td>
        </tr>
    <!-- FIN POUR  -->
    <?php endforeach; ?>
</table>