<h2>Top <?=count($bestEmployees)?> des vendeurs</h2>
<table class="table table-sm table-striped table-hover">
    <tr>
        <th class="px-3">Classement</th>
        <th class="px-3">Nom/Prénom</th>
        <th class="px-3">Bureau</th>
        <th class="px-3">Chiffre d'affaire</th>
    </tr>
    
    <?php foreach($bestEmployees as $key=>$employee) : ?>
    <tr>
        <td class="px-3"><strong>#<?=$key+1?></strong></td>
        <td class="px-3">
            <a href="employee.php?id=<?=$employee['employeeNumber']?>">
            <?=$employee['lastName']?>
            <?=$employee['firstName']?>
            </a>
        </td>
        <td class="px-3"> <?=$employee['city']?></td>
        <td class="px-3"><?=euro($employee['CA'])?></td>
    </tr>
    <?php endforeach; ?>

</table>