<h2>Top <?=count($bestCustomers)?> des clients</h2>
<table class="table table-sm table-striped table-hover">
    <tr>
        <th class="px-3">Client</th>
        <th class="px-3">Chiffre d'affaire</th>
    </tr>
    <?php foreach($bestCustomers as $customer) : ?>
    <tr>
        <td class="px-3">
            <a href="customer.php?id=<?=$customer['customerNumber']?>">
               <?=$customer['customerName']?>
            </a>
        </td>
        <td class="px-3"><?=euro($customer['CA'])?></td>
    </tr>
    <?php endforeach; ?>
</table>