<?php include './templates/blocs/header.phtml' ?>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <h1> <?=$employee['lastName']?> <?=$employee['firstName']?></h1>
                    <h2><?=$employee['jobTitle']?></h2>
                    <h3><?=$employee['email']?></h3>
                    <p><strong>N+1&nbsp;: </strong><a href="employee.php?id=<?=$boss['employeeNumber']?>"><?=$boss['lastName']?> <?=$boss['firstName']?></a></p>
                </div>
                <div class="col-4">
                    <h4>C.A. effectué&nbsp;: <?=$employee['CA']?></h4>
                    <h4>Bureau&nbsp;: </strong><a href="office.php?id=<?=$employee['officeCode']?>"><?=$employee['state']?> - <?=$employee['country']?></a></h4>

                    <p>
                        <strong>Tél.&nbsp;: </strong><?=$employee['phone']?><br>
                        <strong>Adresse&nbsp;: </strong><br>
                        <?=$employee['addressLine1']?><br>
                        <?php if($employee['addressLine2'] != ""):?>
                            <?=$employee['addressLine2']?><br>
                        <?php endif;?>
                        <?=$employee['postalCode']?> - 
                        <?=$employee['country']?> - 
                        <?php if($employee['state'] != ""):?>
                            <?=$employee['state']?> - 
                        <?php endif;?>
                        <?=$employee['territory']?>
                    </p>
                    
                </div>
            </div>
        </div>
    </header>
    <main>
        <section id="order-detail">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h2>Commandes de ses clients</h2>
                        <table class="table table-sm table-striped table-hover">
                            <tr>
                                <th class="px-3">Numéro de commande</th>
                                <th class="px-3">Client</th>
                                <th class="px-3">Date</th>
                                <th class="px-3">Due le</th>
                                <th class="px-3">Expédiée le</th>
                                <th class="px-3">Status</th>
                                <th class="px-3">Nb pièces</th>
                                <th class="px-3">Total</th>
                            </tr>
                                <?php foreach($orders AS $order) : ?>
                                    <tr>
                                        <td class="px-3">
                                            <a href="order.php?id=<?=$order['orderNumber']?>">
                                                <?=$order['orderNumber']?>
                                            </a>
                                        </td>
                                        <td class="px-3"><a href="customer.php?id=<?=$order['customerNumber']?>"><?=$order['customerName']?></a></td>
                                        <td class="px-3"><?=$order['orderDate']?></td>
                                        <td class="px-3"><?=$order['requiredDate']?></td>
                                        <td class="px-3"><?=$order['shippedDate']?></td>
                                        <td class="px-3">
                                        <?php 
                                            $status="success";
                                            if($order['status']=='Cancelled'){
                                                    $status='danger';
                                            } elseif($order['status']=='Disputed'){
                                                $status='warning';
                                            } elseif($order['status']=='In Process'){
                                                $status='primary';
                                            }
                                        ?>
                                        <span class="badge text-bg-<?=$status?>">
                                            <?=$order['status']?>
                                        </span><br>
                                        </td>
                                        <td class="px-3"><?=$order['quantity']?></td>
                                        <td class="px-3"><?=euro($order['total'])?></td>
                                    </tr>
                                <?php endforeach; ?>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </main>
<?php include './templates/blocs/footer.phtml' ?>