<?php include './templates/blocs/header.phtml' ?>
    <header>
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1>Résultats de la recherche</h1>
                </div>
            </div>
        </div>
    </header>
    <main>
        <div class="container">
            <div class="row">
                <div class="col">
                    <ul>

                        <li>
                            <a href="product.php?id=XXXXXX">Nom du produit (#XXXXXX)</a> 
                        </li>

                    </ul>
                </div>
            </div>
        </div>
    </main>
<?php include './templates/blocs/footer.phtml' ?>